### ISSUE TITLE
[Bug]: Max power to Grid

### ISSUE THREAD

**Issue by fofo444** [victronenergy/dynamic-ess#65] opened 2023-09-15 17:16 UTC
### Contact Details

fofo444@gmail.com

### VRM portal ID

b827eb779d5c

### Country / region

Slovakia (sk)

### B max

14

### TB max

5

### FB max

5

### TG max

2.5

### FG max

2.5

### Battery costs

0.04

### Buy price

0.254

### Sell price

p

### feed-in possible

yes

### feed-in possible

yes

### What happened?

Setting max power baterry to grid 2500. Maximum feed-in 2800w. Real delivery to grid 3136w. 

![f1](https://github.com/victronenergy/dynamic-ess/assets/47315071/88802cc9-9505-46ee-8fa7-4f8260c67fab)
![F4](https://github.com/victronenergy/dynamic-ess/assets/47315071/72629e80-b5ef-40a0-96ff-d8e3a9efc5bb)
![F2](https://github.com/victronenergy/dynamic-ess/assets/47315071/62c6d4cf-c28b-4d58-b586-e4cccc17445f)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment] 2023-09-15 20:11
Thanks for reporting and the clear report and screenshots. We'll take a look at it next week.

**Comment by dirkjanfaber** [comment] 2023-09-19 13:50
Duplicate of issue #69 .

**Closed by dirkjanfaber** 2023-09-19 13:50 UTC
Labels: bug

**Comment by fofo444** [comment] 2023-09-20 17:25
It's not a duplication. he problem persists. This problem is when discharging the battery to the grid. I can supply a maximum of 3kW. I have set a limit of 2.5kW. And the system supplies 3.1 kW.

**Comment by fofo444** [comment] 2023-09-20 20:37
Tested on candidate version. Into the grid goes 2.8kW. Dess set to 2.5. In the graph is 2.5. Is it okay?
