### ISSUE TITLE
[VRM - Bug]: Status about dynamic ESS and before

### ISSUE THREAD

**Issue by pokeplayer2** [victronenergy/dynamic-ess#106] opened 2023-10-17 06:44 UTC
### VRM portal ID

b827eb6ff17f

### Country / region

Germany (de)

### B max

26

### TB max

6,5

### FB max

7

### TG max

30

### FG max

30

### Battery costs

0,02

### Buy price

p+0.217+0.0161

### Sell price

0,115

### feed-in possible

yes

### feed-in control

yes

### What happened?

Here is the status of the dynamic ESS solution before I switched on and when it is on.

### When did it happen?

13/10/2023 07:00

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by pokeplayer2** [comment] 2023-10-17 06:51
09/1010/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/1db21b5e-c6b1-44ac-9799-f808373efc7d)

10/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/d1f61d27-2f01-4f0e-8f58-6a9b5f142f58)

11/102023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/8e5b4fbf-0455-40b6-af17-ffe340bc1edb)

12/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/8b645a66-eadd-4a5b-90e1-62fe490e240b)

13/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/e042af61-45db-4164-b33d-c4be08307da5)

14/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/f8b8749c-3f64-485a-9403-1a81468ea761)

15/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/b4ed1a20-140b-4ffc-9162-c1d273fd88d4)

16/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/f0e20e5b-a6b2-4a73-8df3-68393d3279a3)

Overall, we buy too much from grid during the expensive time with dynamic ESS.  -> I will check another solution or go back to the old script.

**Comment by dirkjanfaber** [comment] 2023-10-17 09:49
This is confusing. Your overview has a lot more costs than we can deduce. Your grid readings wildly differ from what is shown and recorded in VRM. 
For example your grid numbers (as recorded for the 16th of October):
![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/3f988046-a638-40a5-be17-a3858ab3dc3d)

Which does not seem to match you graphs. From what measurements are your graphs coming from? If we check the VRM recorded measurements of L1, L2 and L3 from between 4:00 and 5:00, we are unable to match those to the 0.66 kWh grid usage your graph is showing:
![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/3a24245b-0571-43c1-8031-728379b664d7)

You are of course free to use whatever system you want and works for you. If the calculations happen with wrong data and assumptions, it is not surprising that the wrong actions are taken. At the moment that looks specific for your site, so it is interesting to check where the cause of getting the wrong values lies. And you are sure that this started when you enabled DESS? Or did more things change on your setup?

Also, which "old script" are you referring to?

**Comment by pokeplayer2** [comment] 2023-10-17 13:29
Thx for your feedback, since Friday is the API to get the grid data down for my power provider :-(  
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/e6df8a80-0a9a-458e-9018-71d6c56a9d1c)
so I can't trust them and VRM is correct. That is terrible, just when I start to test dynamic ESS was the API "down". All local screenshots are correct, but the screenshots from grid power company a wrong from 13/10/2023.

**Comment by dirkjanfaber** [comment] 2023-10-17 13:56
Admittedly I had not expected that, but at least it does explain the differences. Hope that your provider fixes their API issues soon, so we can really compare the numbers. 
If you don't mind I'll close this issue now. Please do create a new one when their API works again and the numbers don't match.

**Closed by dirkjanfaber** 2023-10-17 13:56 UTC
Labels: bug, VRM
