### ISSUE TITLE
[Bug]: Dynamic ESS charges from grid instead of PV only

### ISSUE THREAD

**Issue by idstein** [victronenergy/dynamic-ess#80] opened 2023-09-21 14:14 UTC
### Contact Details

paul@strawder.info

### VRM portal ID

dca6329bad96

### Country / region

Germany (de)

### B max

15.5152

### TB max

4.2

### FB max

3.36

### TG max

15

### FG max

28.5

### Battery costs

0.04

### Buy price

0.359

### Sell price

p*0.97

### feed-in possible

yes

### feed-in control

yes

### Version

0.1.6

### What happened?

Charge / Discharge control produces additional cost when based on SoC targets only.

Given a DESS plan based on SoCs it can not adapt in the morning and evening hours properly to varying energy solar production.

See attached screenshot how the DESS continues to charge the battery (default grid set point is 0 to avoid grid consumption due to higher prices).

![image](https://github.com/victronenergy/dynamic-ess/assets/743561/fbc10889-9937-42a6-98ca-aee34e650ce2)

DESS schedule
![image](https://github.com/victronenergy/dynamic-ess/assets/743561/a843da7f-e427-497f-8a1a-f9587768170c)

Additionally, there is no adjustment when the predicted SoC consumption per hour deviates. For instance over night there seems to be a little bit higher consumption then predicted, but the DESS schedule forces a const lower discharge instead of switching to controlling via grid set point 0.

Without DESS grid consumption can be really minimised
![image](https://github.com/victronenergy/dynamic-ess/assets/743561/93867f59-d0fe-480d-9588-e906c47d44e7)

When using DESS often in the morning there is an additional load due to the sharp rises of production. Maybe there should be an additional backoff battery reserve definition to deal with variances in the prediction.
![image](https://github.com/victronenergy/dynamic-ess/assets/743561/b127828f-b4f8-4f9e-90cc-f4655fc8f8fb)
 

VenuOS is running on version 3.20~2.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by disaster123** [comment] 2023-09-21 15:10
This seems to be a duplicate of https://github.com/victronenergy/dynamic-ess/issues/79

**Comment by dirkjanfaber** [comment] 2023-09-22 07:29
It looks like you have the minsoc set to zero. Can you try increasing that to 10%?

**Comment by wetty** [comment] 2023-09-22 09:13
Hi
your Sell Price
p*0.97
ist correct?

Normally for newer system it is less then 10 cent in Germany.

**Comment by idstein** [comment] 2023-09-22 09:27
For sell price my understand was that `p` expresses the current EPEX spot price. The 0.97 should translate into a 3% fee subtracted from the spot price.

Added now 10% MinSoC in ESS settings and will monitor the system. Consumption data should be available for almost half a year in VRM. @dirkjanfaber which data needs to be built-up?

**Comment by wetty** [comment] 2023-09-22 09:32
Sell Price is the price you get. Einspeisevergütung.

Or do you do sell direct? "Direkt Vermarktung" like Jörg from meintechblog.de

**Comment by idstein** [comment] 2023-09-22 09:34
Sell Price is either a constant value like `0.0671` like the EEG-Einspeisevergütung or a variable sell price as for my case with `Marktprämien Direktvermarktung` often linked to EPEX Spot price `p`

**Comment by dirkjanfaber** [comment] 2023-09-27 13:10
We keep the battery stable and not the grid: in our internal testing keeping the battery usage stable (basically the same as the plan) has been a lot more cost-effective than otherwise, because of the battery costs that pile up. 

In order to forecast consumption well, it needs 28 days of consumption data. Solar forecasting should be correctly functioning within a day after setting the location.

Closing this issue now as I believe the original "bug" has been explained by the way the system works.

**Closed by dirkjanfaber** 2023-09-27 13:10 UTC
Labels: bug

**Comment by pahorpet** [comment] 2023-10-01 18:19
Hi @dirkjanfaber 
thank you for taking care of the issue,
I would like to add also a note to it as I see some issue regarding planing the consuption as well, seen here Dynamic ESS - d41243d31a1a (CZ)

As there is a battery cost setting, I would expect that it should react on that and if battery cost is set to 0 or close to 0 like 0.001, there should be no cost to "pile up". 

So hold grid to defined setpoint "0" or "-10" would make sence or?
I have seen that is buying some energy from grid never less there is enought battery (> SOC lim ) and not use it and the consuption is fully from grid. As the energy forecast was not accurate and it stick to the plan anyway.

DESS not allow to the grid as spot <0
![2023-10-01_14h19_12](https://github.com/victronenergy/dynamic-ess/assets/34677832/76139fd6-daac-44bf-8f8f-99deeb549b33)

Selling anyway !!!
![2023-10-01_14h19_31](https://github.com/victronenergy/dynamic-ess/assets/34677832/29a67a9a-7907-4bb1-abbb-267c9acb2fca)

ESS set manually to not allow to sell.
![2023-10-01_14h27_57](https://github.com/victronenergy/dynamic-ess/assets/34677832/e5fcf790-728b-43fb-84ff-ea6cd6590a60)

Is there any way to change the behavior to ignore SOC value and stop selling?
Is there any way to stop charging from the grid if price is higher that sell in next few hours as the plan for consuption is not possible to guess for longer period.
Is there any way to stop charging from the grid if solar forecast is higher then expected consuption?

Thank you
