### ISSUE TITLE
[Bug]: ver 0.1.1: actual discharging way too low to meet planned SOC level

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#54] opened 2023-09-12 19:21 UTC
### Contact Details

siempoot@gmail.com

### VRM / Site iD

c0619ab31cc4

### Country / region

Netherlands (nl)

### B max

40

### TB max

5

### FB max

7

### TG max

16

### FG max

16

### Battery costs

0.027

### Buy price

(p+0.13)*1.21+0.02

### Sell price

(p+0.13)*1.21+0.02

### feed-in possible

yes

### feed-in possible

yes

### What happened?

After enabling the new 0.1.1 version, the schedule planned to lower the battery with 15% in one hour (about 6kwh). To reach this I would expect the Multiplus (3x) would have to do some serious work. However it took  around 300 to 400 watt from the battery. Also next hour, also with a plan to lower with 15%, exactly the same. 

And after 9pm, it still has the plan to lower the SOC, but instead it is charging with around 300 watt from the grid.

I have no errors and the install went fine. What is the problem?

![VESS - Screenshot 2023-09-12 212042](https://github.com/victronenergy/dynamic-ess/assets/139110412/40588112-7fc3-4b90-a25a-a8a3d0a30dfc)
![VESS - Screenshot 2023-09-12 211956](https://github.com/victronenergy/dynamic-ess/assets/139110412/6b9669a4-878c-4d4a-a575-829b16b1a91c)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by LecramRed** [comment] 2023-09-12 19:52
I had that too. After deleting the dess flow and restarting Node Red, the discharge current has increased a lot

**Comment by dirkjanfaber** [comment] 2023-09-12 20:39
At the moment your target SOC is set to 31% with the battery SOC at 31.2%

<img width="565" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/cd202476-6d24-41ce-90dd-67fa81f47be6">

Please allow the system to run for a while. We'll take a closer look when needed.

**Comment by LecramRed** [comment] 2023-09-13 03:30
Target is now 56%, actual soc 42%. Charge power is now 220W. Isn't that way too low for a 12 kwh battery?

**Comment by LecramRed** [comment] 2023-09-13 04:45
Last hour, the target was 69%, but the current was way too low to achieve this and reached only less than 50 at the end of the hour. It's target is now 57%, 15 minutes to go, 50% soc and 200 W charge power. Something is going wrong.

**Comment by LecramRed** [comment] 2023-09-13 06:13
![image](https://github.com/victronenergy/dynamic-ess/assets/100309229/e11c655f-7d8a-4d79-811e-8fc835315101)
![image](https://github.com/victronenergy/dynamic-ess/assets/100309229/28b5743f-0c10-4e9f-a1fc-e22ac044d8fa)

Target is 11%, estimated discharge is about 3.5 kWh, but the discharge power is about 800W. It will not achieve it's soc target in this way.

**Comment by dirkjanfaber** [comment] 2023-09-13 06:15
Totally agreeing that it looks like there is a problem right now. Investigating the cause.

**Comment by LecramRed** [comment] 2023-09-13 06:17
Together we make it great!

**Comment by dirkjanfaber** [comment] 2023-09-13 06:55
Can you add the following to your flow?
```
[
    {
        "id": "11c0695b7819894f",
        "type": "group",
        "z": "89827d782ab51de2",
        "name": "Store battery capacity",
        "style": {
            "label": true
        },
        "nodes": [
            "e9a9bebc9c4732d0",
            "b48a8f507e14330a",
            "b68ffdbbf4152cf3",
            "8d723ea6a3f644bc"
        ],
        "x": 54,
        "y": 819,
        "w": 1092,
        "h": 82
    },
    {
        "id": "e9a9bebc9c4732d0",
        "type": "change",
        "z": "89827d782ab51de2",
        "g": "11c0695b7819894f",
        "name": "battery capacity",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "dess.options.b_max",
                "tot": "flow"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 260,
        "y": 860,
        "wires": [
            [
                "b68ffdbbf4152cf3"
            ]
        ]
    },
    {
        "id": "b48a8f507e14330a",
        "type": "victron-output-custom",
        "z": "89827d782ab51de2",
        "g": "11c0695b7819894f",
        "service": "com.victronenergy.settings",
        "path": "/Settings/DynamicEss/BatteryCapacity",
        "serviceObj": {
            "service": "com.victronenergy.settings",
            "name": "com.victronenergy.settings"
        },
        "pathObj": {
            "path": "/Settings/DynamicEss/BatteryCapacity",
            "name": "/Settings/DynamicEss/BatteryCapacity",
            "type": "number"
        },
        "name": "",
        "onlyChanges": false,
        "x": 880,
        "y": 860,
        "wires": []
    },
    {
        "id": "b68ffdbbf4152cf3",
        "type": "change",
        "z": "89827d782ab51de2",
        "g": "11c0695b7819894f",
        "name": "to number",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "$number(payload)",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 450,
        "y": 860,
        "wires": [
            [
                "b48a8f507e14330a"
            ]
        ]
    },
    {
        "id": "8d723ea6a3f644bc",
        "type": "link in",
        "z": "89827d782ab51de2",
        "g": "11c0695b7819894f",
        "name": "link in 1",
        "links": [
            "0a258a4a88409834"
        ],
        "x": 95,
        "y": 860,
        "wires": [
            [
                "e9a9bebc9c4732d0"
            ]
        ]
    }
]
```

**Comment by LecramRed** [comment] 2023-09-13 06:58
I would love to, but would you please tell me how to add and where?

**Comment by dirkjanfaber** [comment] 2023-09-13 07:02
Sure. You can import this into Node-RED via the ctrl-i / command-i / via the menu and then pasting it into the text area.

<img width="247" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/b82d89b3-738a-4ff1-acd8-e52d36d80ecc">

<img width="695" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/04651a8a-6498-430c-8aa5-a9907352842d">

**Comment by LecramRed** [comment] 2023-09-13 07:05
Thanks, I have done it. What should it do? Where do I have to pay attention to, so that I can inform you about the results?

**Comment by dirkjanfaber** [comment] 2023-09-13 07:12
For now we need to wait a few hours to see if the target SOC is indeed being followed by the battery. I'll keep an eye on your site as well.

If you encounter strange things in the mean time, just update this issue.

**Comment by LecramRed** [comment] 2023-09-13 08:13
be aware that I have an battery expansion planned for today, I will double the capacity from 12 to 24 kWh. That can disturb the process somewhat

**Comment by dirkjanfaber** [comment] 2023-09-13 09:23
That should not be a problem if you:
- update to 0.1.2 (which fixes copying the configured value of `b_max` to the context)
- update the battery capacity in the flow

Afterwards you can check in the context data if your flow contains 24 instead of 12 for `b_max` (14 in this example screenshot)

<img width="306" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/35043b87-6565-4f6f-b260-73c4bea34e2c">

**Comment by SimonYoungtree** [comment] 2023-09-13 09:47
> Sure. You can import this into Node-RED via the ctrl-i / command-i / via the menu and then pasting it into the text area.
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/3098947/267564611-b82d89b3-738a-4ff1-acd8-e52d36d80ecc.png"> <img alt="image" width="695" src="https://user-images.githubusercontent.com/3098947/267564356-04651a8a-6498-430c-8aa5-a9907352842d.png">
> That will give you this extra piece of flow: <img alt="image" width="1116" src="https://user-images.githubusercontent.com/3098947/267564857-15e27445-06aa-4dfe-b826-364e2397e08e.png">
> 
> Put it somewhere on the canvas and then redeploy the flow. That should do the trick.

I also did the update and I have added the flow

**Comment by dirkjanfaber** [comment] 2023-09-13 14:34
Looking at a graph of vrm logging, I see that the battery SOC (yellow) is following the target SOC (green) nicely. So I'll close this issue.

<img width="303" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/b40471b7-d1f7-4cc3-a123-397c579cf2be">

**Closed by dirkjanfaber** 2023-09-13 14:34 UTC
Labels: bug
